### ISSUE TITLE
Pan and zoom is not working in  ie 11 on windows 8 touch screen 

### ISSUE THREAD

**Issue by rahul-avaghan** [mvindahl/angular-pan-zoom#46]
hello ,
I have a question.
1. Whether the plug-in supports pan and zoom feature in  internet explorer 11 on windows 8 touch PC.
  If it doesn't not supports Please suggest hints to implement the same.

**Comment by mvindahl** [comment]
Hi @superdexter,
I'm afraid that I have to say that I have no idea if the directive works in the given configuration and I have no device on which I can test it. If you have such a device, I think you can easily test it using the online demo at http://htmlpreview.github.io/?http://rawgithub.com/mvindahl/angular-pan-zoom/master/demo/demo.dev.html. (As I suspect that you may have already done :) )

If you find that it does not work, I think the next step in locating the error would be to try IE11 on both touch devices and mouse controlled devices; and to try different browsers on the Win8 touch device. That may give us a clue.

**Comment by superdexter** [comment]
Hello martin,
Below are my observation for windows 8 touch PC
ie 11 - Pan works with (-ms-touch-action:none) &  zoom does-not works .When we zoom image on internent explorer entire page gets zoomed instead of only image.
chrome-zoom and pan works
mozilla- zoom and pan works but zoom is not smooth.Takes little effort to zoom image through pinch getsture .

and pan & zoom feature works perfectly in ie 11 on mouse controller device

**Comment by mvindahl** [comment]
Hello @superdexter,
Apologies for late reply. I don't really have the hardware to debug this, let alone fix it, but of course any pull requests would be welcomed. Judging by the description it would seem that in IE, the browser receives the pinch event instead of the directive. It's hard for me to tell for sure if the directive gets the event but fails to stop propagation, or if it doesn't get it at all. Probably the latter.

Here is another library which seems to have solved the problem: https://github.com/timmywil/jquery.panzoom/issues/68

Maybe we could learn something from their experiences.

**Comment by superdexter** [comment]
I have tried mentioned approach.The zoom works for the first time then it does not work at all.
    As per my studies on net , it suggests that for pinch gesture to work properly on ie11 windows touch PC we have to use pointerevents(http://www.w3.org/TR/pointerevents/) 
.Pointer events supports (Mouse,Pen,touch) or any combination of these three.
I hope we don't require any hardware since same event will be fired for any of the three things. 
 correct me if my perspective is wrong :p
