### ISSUE TITLE
NPM version of angular-pan-zoom needs bower

### ISSUE THREAD

**Issue by btinoco** [mvindahl/angular-pan-zoom#49]
I was trying to install the angular-pan-zoom directive via npm but it failed with "bower is not installed" does the npm version of angular-pan-zoom depends on bower?  My project is not using bower and I would hate to install it just to use the directive. :(

**Comment by mvindahl** [comment]
Hello btinoco,

I'm a bit puzzled by the error. It's true that the project relies upon bower, mainly for historical reasons, but that should merely have the effect of installing bower as a dependency when doing npm install, and then letting bower fetch its dependencies in the postinstall step. It shouldn't require you to do anything explicit in order to deal with bower.

To help me reproduce the issue, could you please supply me with the npm command which you use to install angular-pan-zoom, including any flags?

Best regards,
/Martin

**Comment by btinoco** [comment]
Yes, I typed **npm install angular-pan-zoom --save** on windows 7.  I believe it has to do with the fact that I do not have bower installed in my project or globally.

**Comment by mvindahl** [comment]
Yes, you are right, and you are doing things just right. The fact that the npm project relies upon bower is the broken thing here. I've reproduced the error as well now.

Thing is, the libs which bower pull in is not really needed, except for local development. So my plan would be to rearrange the package.json slightly so that bower is not called during the install steps. Expect a fix within the next 24 hours :)

**Comment by mvindahl** [comment]
@btinoco I believe that I have resolved the issue, and I have bumped the version number to 1.0.17.

Could you please confirm that this also solves the problem at your end?

**Comment by btinoco** [comment]
Thank you Martin.  I did the same install **npm install angular-pan-zoom --save** and it worked like a charm. Let me know if you want to close this.

**Comment by mvindahl** [comment]
Hi @btinoco, I'll just close this issue now. Thanks for reporting it, and I'd love to hear of any other issues which you may encounter.
Cheers,
/Martin
